### ISSUE TITLE
在use-amd中遇到的一个问题

### ISSUE THREAD

**Issue by moonye6** [fex-team/fis3-demo#20]
切换到`use-amd`目录下面，安装需要的包
执行`fis3 release  -d ./dist`，一切正常

再执行一次 `fis3 release  -d ./dist`，会发现有报错，且dist目录下又生成了一个dist目录

```

 Ω ........
 [WARNI] Onymous module `comp/1-0/1-0` is not allowed here in `/dist/static/comp/1-0/1-0.js`, but it will be erased anyway.
.
 [WARNI] Onymous module `comp/2-0/2-0` is not allowed here in `/dist/static/comp/2-0/2-0.js`, but it will be erased anyway.
.
 [WARNI] Onymous module `comp/cal/cal` is not allowed here in `/dist/static/comp/cal/cal.js`, but it will be erased anyway.
...... 757ms
```

如果你执行`fis3 release -w -d ./dist`，然后随便改一个文件如index.html，会发现，会生成很多dist目录，一层嵌一层
![image](https://cloud.githubusercontent.com/assets/9132408/9566729/46dfc91e-4f43-11e5-930b-148391054d84.png)

**Comment by oxUnd** [comment]
把产出产出到代码目录以外就好了

```
fis3 release -d ../dist
```

**Comment by 2betop** [comment]
出现这个问题的原因，产出文件再次经历一次编译。 fis3  中默认的忽略产出目录是 'output' ， `dist` 是不在忽略列表里面的，请把这个设置上传，或者你把产出改成 output 目录。

**Comment by moonye6** [comment]
恩 两种方式都可行的 
第二种是修改fis3/lib/config.js中代码

```
  project: {
    charset: 'utf8',
    md5Length: 7,
    md5Connector: '_',
    files: ['**'],
    ignore: ['node_modules/**', 'output/**', '.git/**', 'fis-conf.js', 'dist/**']
  },
```
