### ISSUE TITLE
[fis3-angular]如何动态加载bower.json中定义的依赖呢？

### ISSUE THREAD

**Issue by zxkane** [fex-team/fis3-demo#33]
[fis3-angular](https://github.com/zhangtao07/fis3-angular-demo) 通过`bower.json`定义了依赖的库，如何通过`mod`动态加载这些依赖？而不是把它们都引用在`index.html`从开始就加载?

项目的依赖已经通过`bower install`安装到了本地。但是第三方js并没有引用在`index.html`。我尝试把`bower_components`下的js库发布到modules目录下。

`fis-conf`中定义了如下规则，

```
fis.match(/^\/bower_components\/the-library\/dist\/library\.js/i, {
    isMod : true,
    id : 'library',
    release : '${statics}/modules/library/library.js'
})
```

fis完全忽略了此规则，并没有把`bower_components`下的library发布到`modules`目录下。看起来fis3会忽略没有include在index.html中的js。有什么办法可以实现动态加载(**require(lib)**)bower安装的第三方js库？

**Comment by zhangtao07** [comment]
因为 bower 里面有很多冗余资源，为了提升编译速度才采取了这种按需加载的方式：

``` js
fis.set('project.files', ['page/**', 'map.json', 'modules/**', 'lib']);
```

没有默认处理 bower_components文件夹，根据index.html 显式加载文件来声明以实现按需加载所需资源。当然如果你去掉这种限制就跟普通的 FIS 依赖分析一样了

**Comment by zxkane** [comment]
已用相似方法做到。多谢确认。
