### ISSUE TITLE
使用modjs时依赖关系怎么办呢？如bootstrap依赖jquery

### ISSUE THREAD

**Issue by iamllitog** [fex-team/fis3-demo#38]

**Comment by 2betop** [comment]
```
fis3 install bootstrap
```

然后会自动下载 bootstrap 和 jquery

然后你直接能通过 bootstrap 来引用他的资源如：`require('bootstrap')` `<link href="bootstrap/css/button.css />"` 之类的。

建议看下 https://github.com/fex-team/fis3-demo/tree/master/components-mod-demo

**Comment by iamllitog** [comment]
麻烦问下，那如果不用fiscomponents可不可以呢？

**Comment by 2betop** [comment]
可以，可以在对应的模块化插件中去配置 paths 或者 packages 支持别名。

**Comment by iamllitog** [comment]
我用的fis3-hook-common这个插件，shim也可以配置么0.0

**Comment by 2betop** [comment]
bootstrap 里面确实没有写 require('jquery') 莫非你要自动给补上这个？

fis3-hook-amd 有 shim, commonjs 还没有

**Comment by iamllitog** [comment]
TT好吧，也只能先用amd了，期望以后cmd模式可以使用packto和shim等操作
