### ISSUE TITLE
'fis3-hook-modules' is not in the npm registry

### ISSUE THREAD

**Issue by springuper** [fex-team/fis3-demo#4]
[use-php](https://github.com/fex-team/fis3-demo/tree/master/backend-resource-manage/use-php) demo requires 'fis3-hook-modules', but it's not in the npm registry now.

**Comment by oxUnd** [comment]
```
npm install -g fis3-hook-module
```

**Comment by springuper** [comment]
https://github.com/fex-team/fis3-demo/pull/8
