### ISSUE TITLE
fis将文件打包到指定的文件里面去

### ISSUE THREAD

**Issue by ghost** [fex-team/fis3-demo#41]
场景：
      首页文件有两个，一个index.html(里面使用的是cdn)，还有一个本地的indexLocal.html(没有使用cdn)，如何使用一个media，同时打包这两个文件，并且，使用cdn的文件，打包的时候，里面的cdn链接不变。

**Comment by yanmingfei** [comment]
你这个是资源定位的问题，就是输出到指定目录，并且，它还可以指定html中引入的地址。
http://fis.baidu.com/fis3/docs/user-dev/uri.html
