### ISSUE TITLE
参考use-amd Demo配置我发布之后的代码，顺序不对

### ISSUE THREAD

**Issue by w3cpress** [fex-team/fis3-demo#44]
请教 我按照use-amd 里面的方法配置的。为什么我prod出来的代码，合并压缩的代码顺序不对。我如何保证按照执行顺序合并呢？

**Comment by Baiang** [comment]
我也遇到类似问题，通过升级FIS3解决的

**Comment by w3cpress** [comment]
这个我已经知道怎么弄了，嘿嘿
