### ISSUE TITLE
请问有没有详细开发插件的文档

### ISSUE THREAD

**Issue by Baiang** [fex-team/fis3-demo#48]
请问有没有详细开发插件的文档

**Comment by allincache** [comment]
你好，我这边没有相关文档。你可以上fis官网或google查查试试。

在 2016-05-09 17:54:11，"Yang Weiwei" notifications@github.com 写道：

请问有没有详细开发插件的文档

**Comment by marsDes** [comment]
现在nodejs 已经是6.2的 fis3 只支持4.版本吗

**Comment by 2betop** [comment]
fis3  3.4 起支持  6.x

**Comment by 2betop** [comment]
http://fis.baidu.com/fis3/docs/api/dev-plugin.html
