### ISSUE TITLE
fis3打包为什么会把未处理的文件全部复制一遍到新的目录

### ISSUE THREAD

**Issue by zhaoqize** [fex-team/fis3-demo#56]
fis3打包的时候我只想处理一个js文件,可是别的文件跟文件夹也被复制到了新的目录？为什么会这样？

**Comment by hwenjie** [comment]
fis.set('project.ignore', [
  '.git/**',
  'node_modules/**',
  '.gitignore',
  'README.md',
  'package.json'
]); 
/*排除文件*/

**Comment by hwenjie** [comment]
fis.set('project.ignore', [
  '.git/**',
  'node_modules/**',
  '.gitignore',
  'README.md',
  'fis-conf.js',
  'favicon.ico',
  'init.php',
  'package.json',
  'v.html',
  'v.js'
]); /*排除文件*/

**Comment by hwenjie** [comment]
fis.set('project.ignore', [
    '.git/**',
    'node_modules/**',
    '.gitignore',
    'README.md',
    'package.json'
]); /_排除文件_/

**Comment by zhaoqize** [comment]
谢谢  按照你的这么写就可以了。
但是每次都要这么主动的去设置这个么？

**Comment by hwenjie** [comment]
什么每次设置？ 这是配置文件啊，写完就很少动了

**Comment by zhaoqize** [comment]
@hwenjie 大神大神  别走 我还有个问题请教。
就是fis怎么去删除一个文件或文件夹呢？应该怎么配置的呢？

**Comment by hwenjie** [comment]
@zhaoqize 不会，我是新手

**Comment by zhaoqize** [comment]
@hwenjie  - -||  多谢
