### ISSUE TITLE
fis3配置问题。求解救。 main.less文件中所@import的less文件没有被编译,

### ISSUE THREAD

**Issue by doubleHao2** [fex-team/fis3-demo#64]
fis3配置问题。求解救。 main.less文件中所@import的less文件没有被编译,怎么破

项目结构如下图。main.less里引入了lib下的两个less文件，希望最后产出到content/main.css文件中,是产出了，但产出的main.css文件内容是这样的：

@import lib/_reset.less

@import lib/_common.less

.header {

***

}

.box-main {

***

}

也就是说引入lib下的文件没有给编译成css后植入进来，而是直接把两行代码原封不动的丢了进来

**Comment by doubleHao2** [comment]
fis3配置问题。求解救。 main.less文件中所@import的less文件没有被一起编译到main.css,怎么破

项目结构如下图。main.less里引入了lib下的两个less文件，希望最后产出到content/main.css文件中,是产出了，但产出的main.css文件内容是这样的：

@import lib/_reset.less

@import lib/_common.less

.header {

}

.box-main {

}

也就是说引入lib下的文件没有给编译成css后植入进来，而是直接把两行代码原封不动的丢了进来

**Comment by doubleHao2** [comment]
fis3配置问题。求解救。 main.less文件中所@import的less文件没有被一起编译到main.css,怎么破

项目结构如图   https://pic3.zhimg.com/v2-3eccb72f28fefa4d2fa17d2a4d8e1e16_b.png

main.less里引入了lib下的两个less文件，希望最后产出到content/main.css文件中,是产出了，但产出的main.css文件内容是这样的：

@import lib/_reset.less

@import lib/_common.less

.header {

}

.box-main {

}

也就是说引入lib下的文件没有给编译成css后植入进来，而是直接把两行代码原封不动的丢了进来

**Comment by oxUnd** [comment]
#65
