### ISSUE TITLE
请问下该构建工具如何和thinkphp结合使用

### ISSUE THREAD

**Issue by Yxliam** [fex-team/fis3-demo#66]
请问下该构建工具如何和thinkphp结合使用

**Comment by oxUnd** [comment]
1. 你可以先熟悉一下 BS 架构
2. thinkphp 只是个后端框架而已，至于 template 用什么这个你可以选择，比如用 smarty 你就用 smarty 的解决方案。如果是纯 php 可以参考纯 php 的解决方案。如果是纯前端项目，跟 thinkphp 就没有关系了。你可以选择任意一个 vue 或者 react 或者 xxx 前端框架来实现功能。
