### ISSUE TITLE
请问rewrite 和 test 特性有计划加到 fis3 use-smarty demo里么？

### ISSUE THREAD

**Issue by kaiye** [fex-team/fis3-demo#7]
前段时间研究了 fis-plus 发现挺适合我们项目的，今儿发现fis3正式发布了，在考虑要不要换成fis3的内核

**Comment by oxUnd** [comment]
请参考

https://github.com/fex-team/fis3-smarty

**Comment by oxUnd** [comment]
自带 rewirte，test 等的支持。

**Comment by kaiye** [comment]
看到里面引用的server，试用过确实可以，谢谢。 https://github.com/fis-dev/fis-plus-server-framework
