### ISSUE TITLE
请求增加 components-cmd-demo 

### ISSUE THREAD

**Issue by nimoc** [fex-team/fis3-demo#9]
[use-seajs](https://github.com/fex-team/fis3-demo/tree/master/use-seajs) 是打包 cmd 模块。

希望增加一个 components 转 cmd 的插件，因为我们的业务场景下可以用 seajs + cmd + nginx-http-concat 做在线combo的解决方案，不做 all in one 打包。

**Comment by FarmanYu** [comment]
应该用了fis这个打包之后，就不需要combo打包了。

**Comment by nimoc** [comment]
@FarmanYu 
可以关注一下我这里写的 combo 方案 https://github.com/fex-team/fis/issues/638#issuecomment-128263873

这里的components 转 cmd 只是实现插件，具体打包可以选择 动态combo或者fis 分析依赖本地打包
